//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final_354
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.Web;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Clients = new HashSet<Client>();
        }
    
        
        public int GameID { get; set; }

        [Display(Name = "Game Name")]
        [Remote("isExists", "Games", ErrorMessage = "Game name already exist")]
        public string GameName { get; set; }

        [Display(Name = "Release Date(YYYY/MM/DD)")]
        public System.DateTime GameReleaseDate { get; set; }

        [Display(Name = "Number of Platforms")]
        public string GamePlatformCount { get; set; }

        [Display(Name = "Platform Name(exclusives e.g Gears of War)")]
        public string GamePlatformName { get; set; }

        [Display(Name = "Game Genre")]
        public Nullable<int> GameGenreID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        public virtual GameGenre GameGenre { get; set; }
    }
}
